spring:
  datasource:
    name: plateassistant
    url: jdbc:mysql://10.10.3.1/teambiller
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      column-format: "`%s`"
server:
  servlet:
    session:
      timeout: 24h
  port: 8081
